---
-  hosts: routers
   gather_facts: false
   connection: network_cli
   become_method: enable
   
   tasks:
     - name: OSPF R1
       when: ansible_host == "10.29.0.2"
       ios_config:
         parents: router ospf 10
         lines:
           - router-id 1.1.1.1
           - network 192.168.50.0 0.0.0.255 area 0
           - network 10.29.0.0 0.0.0.3 area 0
           - network 10.27.0.0 0.0.0.3 area 0
           - passive-interface FastEthernet0/0

     - name: OSPF R2
       when: ansible_host == "10.29.0.1"
       ios_config:
         parents: router ospf 10
         lines:
           - router-id 2.2.2.2
           - network 172.16.1.0 0.0.0.255 area 0
           - network 10.29.0.0 0.0.0.3 area 0
           - network 10.30.0.0 0.0.0.3 area 0
           - passive-interface FastEthernet0/1

     - name: OSPF R3
       when: ansible_host == "10.30.0.1"
       ios_config:
         parents: router ospf 10
         lines:
           - router-id 3.3.3.3
           - network 152.16.1.0 0.0.0.255 area 0
           - network 10.30.0.0 0.0.0.3 area 0
           - network 10.27.0.0 0.0.0.3 area 0
           - passive-interface FastEthernet0/0     
